import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App'; // Ajustar o caminho se necessário

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);


import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}